groups:
  - name: frontends
    jobs:
      - frontend-build
  - name: services
    jobs:
      - email-alert-service-build

resources:
- name: email-alert-service-git
  type: git
  source:
    branch: concourse
    uri: https://github.com/alphagov/email-alert-service.git
- name: frontend-git
  type: git
  source:
    branch: master
    uri: https://github.com/alphagov/frontend.git
- name: govuk-content-schemas-git
  type: git
  source:
    branch: master
    uri: https://github.com/alphagov/govuk-content-schemas.git

jobs:
- name: frontend-build
  serial: true
  plan:
  - get: frontend-git
    trigger: true
  - get: govuk-content-schemas-git
  - task: tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ruby
          tag: 2.6.1
      run:
        path: sh
        args:
        - -c
        - |
          set -eux

          export GOVUK_CONTENT_SCHEMAS_PATH=`pwd`/govuk-content-schemas-git

          apt-get update
          apt-get install -y nodejs

          cd frontend-git

          bundle install
          bundle exec rake test
      inputs:
      - name: frontend-git
      - name: govuk-content-schemas-git
- name: email-alert-service-build
  serial: true
  plan:
  - get: email-alert-service-git
    trigger: true
  - task: tests
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: amidos/dcind
      run:
        path: sh
        args:
        - -sxc
        - |
          source /docker-lib.sh
          start_docker

          cd email-alert-service-git/ci
          docker-compose build
          docker-compose up --abort-on-container-exit
      inputs:
      - name: email-alert-service-git
